name: One Pace Metadata Job

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run metadata updater
        env:
          GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}
          ONE_PACE_RSS_FEED: ${{ secrets.ONE_PACE_RSS_FEED }}
        run: |
          uv run src/generator.py update
          uv run src/generator.py json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add metadata/episodes metadata/posters metadata/arcs.yml metadata/tvshow.yml
          git diff --cached --quiet || (git add metadata && git commit -m "Add metadata via external sources [automated]")
          git push
