name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run build script (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          export BUILD_OS="windows"
          ./misc/build.sh

      - name: Run build script (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          export BUILD_OS="macos"
          ./misc/build.sh

      - name: Run build script (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          export BUILD_OS="linux"
          ./misc/build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            OnePaceOrganizer-cli-win-x64.exe
            OnePaceOrganizer-cli-macos-arm64
            OnePaceOrganizer-cli-linux-x64
            OnePaceOrganizer-gui-win-x64.exe
            OnePaceOrganizer-gui-macos-arm64.app
            OnePaceOrganizer-gui-macos-arm64
            OnePaceOrganizer-gui-linux-x64
            OnePaceOrganizer-win-x64.zip
            OnePaceOrganizer-macos-arm64.zip
            OnePaceOrganizer-linux-x64.zip
            posters.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
