name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025, windows-11-arm, macos-26]

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run build script (Windows)
        if: contains(matrix.os, 'windows')
        shell: bash
        run: |
          if [[ "$PROCESSOR_ARCHITECTURE" == "ARM64" ]]; then
            export OS_ARCH="arm64"
          fi

          export BUILD_OS="windows"
          ./misc/build.sh

      - name: Set up Homebrew (macOS)
        id: set-up-homebrew
        if: contains(matrix.os, 'macos')
        uses: Homebrew/actions/setup-homebrew@main

      - name: Run build script (macOS)
        if: contains(matrix.os, 'macos')
        shell: bash
        run: |
          export BUILD_OS="macos"
          ./misc/build.sh

      - name: Run build script (Linux)
        if: contains(matrix.os, 'ubuntu')
        shell: bash
        run: |
          export BUILD_OS="linux"
          ./misc/build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            OnePaceOrganizer-cli-windows-x86_64.exe
            OnePaceOrganizer-cli-windows-arm64.exe
            OnePaceOrganizer-cli-macos-arm64.dmg
            OnePaceOrganizer-cli-linux-x86_64
            OnePaceOrganizer-cli-linux-arm64
            OnePaceOrganizer-gui-windows-x86_64.exe
            OnePaceOrganizer-gui-windows-arm64.exe
            OnePaceOrganizer-gui-macos-arm64.dmg
            OnePaceOrganizer-gui-linux-x86_64
            OnePaceOrganizer-gui-linux-arm64
            OnePaceOrganizer-windows-x86_64.zip
            OnePaceOrganizer-windows-arm64.zip
            OnePaceOrganizer-macos-arm64.zip
            OnePaceOrganizer-linux-x86_64.zip
            OnePaceOrganizer-linux-arm64.zip
            posters.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
