name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '>=3.13'
          freethreaded: true

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run build script
        shell: pwsh
        run: .\misc\build.ps1

      - name: Prepare the .zip
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://github.com/ladyisatis/one-pace-metadata/archive/refs/heads/main.zip" -OutFile "metadata.zip"
          Expand-Archive -Path "metadata.zip" -DestinationPath "."
          Remove-Item "metadata.zip"

          Rename-Item "one-pace-metadata-main" "metadata"

          Get-ChildItem -Path "metadata" -File | Where-Object {
              $_.Name -notin @("data.json", "arcs.yml", "tvshow.yml")
          } | Remove-Item -Force

          Get-ChildItem -Path "metadata" -Directory | Where-Object {
              $_.Name -notin @("episodes", "posters")
          } | Remove-Item -Recurse -Force

          Compress-Archive -Path posters -DestinationPath posters.zip

          New-Item -ItemType Directory -Path temp_zip
          Copy-Item dist\OnePaceOrganizer-cli.exe -Destination temp_zip
          Copy-Item dist\OnePaceOrganizer-gui.exe -Destination temp_zip

          Copy-Item -Recurse metadata -Destination temp_zip\metadata
          Copy-Item -Recurse posters -Destination temp_zip\posters

          Compress-Archive -Path temp_zip\* -DestinationPath OnePaceOrganizer-win-x64.zip

          Remove-Item -Recurse -Force temp_zip
          Rename-Item dist\OnePaceOrganizer-cli.exe OnePaceOrganizer-cli-win-x64.exe
          Rename-Item dist\OnePaceOrganizer-gui.exe OnePaceOrganizer-gui-win-x64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/OnePaceOrganizer-cli-win-x64.exe
            dist/OnePaceOrganizer-gui-win-x64.exe
            posters.zip
            OnePaceOrganizer-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
